print ('Esse script é para treino')
print('-----------------------------------')
nome = input('Qual seu nome? ')
idade = input('Qual sua idade? ')
peso = input('E qual seu peso? ')
print()
print('Esse é um belo nome, ', nome)
print ('Vc tem, ', idade + ' anos de idade')
print ('seu peso é, ', peso)
print('-----------------------------------')
print ('Fim do script')
